export const mockData = [
    {
        "guid": "gi3do=",
        "streetAddress": "1096 SE 9th, Suite 100",
        "enableBilltrust": false,
        "blockNonStockPricing": false,
        "city": "Bend",
        "description": "Bend - #267",
        "enabled": true,
        "facebookLink": "https://www.facebook.com/Johnstone-Supply-Bend-105205877902739",
        "faxNumber": "(541) 318-6174",
        "hardiRegionName": "Western",
        "hideLsp": false,
        "instagramLink": "https://www.instagram.com/johnstonenw/",
        "linkedinLink": "https://www.linkedin.com/company/johnstonenw",
        "enableLiveChat": false,
        "liveChatLicenseNumber": "",
        "enableLogin": true,
        "mainStoreCode": "157",
        "phoneNumber": "(541) 318-6135",
        "redirectUrl": "",
        "state": "OR",
        "storeCode": "267",
        "storeEmail": "customerservice.bend@johnstonenw.com",
        "storeHours": "Monday - Friday: 7:00am - 5:00pm<br>  Saturday: CLOSED<br>  Sunday: CLOSED",
        "textPhoneNumber": null,
        "twitterLink": "https://www.twitter.com/Johnstone_NW",
        "useBarcodeScanner": true,
        "useShipToPricing": true,
        "youtubeLink": null,
        "zipCode": "97702",
        "useListPrice": false,
        "displayBranchInPriceBox": false,
        "displayAllOrderNotesData": false,
        "showAlternateDescription": true,
        "showAlternateDescriptionOnAddons": false,
        "maxBranchesVisible": 7,
        "usePromoCode": true,
        "releaseNumberRequired": false,
        "hideBillingAddress": false,
        "orderContactPhoneNumberRequired": false,
        "orderContactEmailRequired": true,
        "enhancedWillCallValueInternal": null,
        "excludeFromEnhancedWillCallInternal": null,
        "enableConfirmEmail": true,
        "enforceAddressValidation": true,
        "useRequiredByDate": false,
        "requiredByDateRequired": false,
        "enableReferral": false,
        "referralRequired": false,
        "enableCreditCard": false,
        "enableCheckoutOrderLimit": false,
        "useNewContact": false,
        "hideSubstituteProductsOnCart": false,
        "overrideAvailabilityMessage": false,
        "hideOrderStatus": true,
        "hideNewAddress": false,
        "hideAddToCartOnBidsAndQuotes": false,
        "mainStore": {
            "country": "US",
            "currency": "USD",
            "description": "Tigard, OR - 16650 SW 72nd Ave. #100",
            "enabled": true,
            "name": "Tigard - #157",
            "posType": "infor",
            "code": "157",
            "state": "OR",
            "zipCode": "97224"
        }
    },
    {
        "guid": "ge=",
        "streetAddress": "11773 SE Capps Road",
        "enableBilltrust": false,
        "blockNonStockPricing": false,
        "city": "Clackamas",
        "description": "Clackamas - #1",
        "enabled": true,
        "facebookLink": "https://www.facebook.com/Johnstone-Supply-Portland-106195381149424",
        "faxNumber": "(503) 231-2553",
        "hardiRegionName": "Western",
        "hideLsp": false,
        "instagramLink": "https://www.instagram.com/johnstonenw/",
        "linkedinLink": "https://www.linkedin.com/company/johnstonenw",
        "enableLiveChat": false,
        "liveChatLicenseNumber": "",
        "enableLogin": true,
        "mainStoreCode": "157",
        "phoneNumber": "(503) 234-7221",
        "redirectUrl": "",
        "state": "OR",
        "storeCode": "1",
        "storeEmail": "cs.portland@johnstonenw.com",
        "storeHours": "Monday - Friday: 7:00am - 5:00pm<br>  Saturday: CLOSED<br>  Sunday: CLOSED",
        "textPhoneNumber": "503-419-9175",
        "twitterLink": "https://www.twitter.com/Johnstone_NW",
        "useBarcodeScanner": true,
        "useShipToPricing": true,
        "youtubeLink": "",
        "zipCode": "97015",
        "useListPrice": false,
        "displayBranchInPriceBox": false,
        "displayAllOrderNotesData": false,
        "showAlternateDescription": true,
        "showAlternateDescriptionOnAddons": false,
        "maxBranchesVisible": 7,
        "usePromoCode": true,
        "releaseNumberRequired": false,
        "hideBillingAddress": false,
        "orderContactPhoneNumberRequired": false,
        "orderContactEmailRequired": true,
        "enhancedWillCallValueInternal": null,
        "excludeFromEnhancedWillCallInternal": null,
        "enableConfirmEmail": true,
        "enforceAddressValidation": true,
        "useRequiredByDate": false,
        "requiredByDateRequired": false,
        "enableReferral": false,
        "referralRequired": false,
        "enableCreditCard": false,
        "enableCheckoutOrderLimit": false,
        "useNewContact": false,
        "hideSubstituteProductsOnCart": false,
        "overrideAvailabilityMessage": false,
        "hideOrderStatus": true,
        "hideNewAddress": false,
        "hideAddToCartOnBidsAndQuotes": false,
        "mainStore": {
            "country": "US",
            "currency": "USD",
            "description": "Tigard, OR - 16650 SW 72nd Ave. #100",
            "enabled": true,
            "name": "Tigard - #157",
            "posType": "infor",
            "code": "157",
            "state": "OR",
            "zipCode": "97224"
        }
    },
    {
        "guid": "gy=",
        "streetAddress": "4027 W 1st Ave",
        "enableBilltrust": false,
        "blockNonStockPricing": false,
        "city": "Eugene",
        "description": "Eugene - #6",
        "enabled": true,
        "facebookLink": "https://www.facebook.com/Johnstone-Supply-Eugene-100286381734308",
        "faxNumber": "(541) 344-8248",
        "hardiRegionName": "Western",
        "hideLsp": false,
        "instagramLink": "https://www.instagram.com/johnstonenw/",
        "linkedinLink": "https://www.linkedin.com/company/johnstonenw",
        "enableLiveChat": false,
        "liveChatLicenseNumber": "",
        "enableLogin": true,
        "mainStoreCode": "157",
        "phoneNumber": "(541) 342-4861",
        "redirectUrl": "",
        "state": "OR",
        "storeCode": "6",
        "storeEmail": "customerservice.eugene@johnstonenw.com",
        "storeHours": "Monday - Friday: 7:00am - 5:00pm<br>  Saturday: CLOSED<br>  Sunday: CLOSED",
        "textPhoneNumber": null,
        "twitterLink": "https://www.twitter.com/Johnstone_NW",
        "useBarcodeScanner": true,
        "useShipToPricing": true,
        "youtubeLink": null,
        "zipCode": "97402",
        "useListPrice": false,
        "displayBranchInPriceBox": false,
        "displayAllOrderNotesData": false,
        "showAlternateDescription": true,
        "showAlternateDescriptionOnAddons": false,
        "maxBranchesVisible": 7,
        "usePromoCode": true,
        "releaseNumberRequired": false,
        "hideBillingAddress": false,
        "orderContactPhoneNumberRequired": false,
        "orderContactEmailRequired": true,
        "enhancedWillCallValueInternal": null,
        "excludeFromEnhancedWillCallInternal": null,
        "enableConfirmEmail": true,
        "enforceAddressValidation": true,
        "useRequiredByDate": false,
        "requiredByDateRequired": false,
        "enableReferral": false,
        "referralRequired": false,
        "enableCreditCard": false,
        "enableCheckoutOrderLimit": false,
        "useNewContact": false,
        "hideSubstituteProductsOnCart": false,
        "overrideAvailabilityMessage": false,
        "hideOrderStatus": true,
        "hideNewAddress": false,
        "hideAddToCartOnBidsAndQuotes": false,
        "mainStore": {
            "country": "US",
            "currency": "USD",
            "description": "Tigard, OR - 16650 SW 72nd Ave. #100",
            "enabled": true,
            "name": "Tigard - #157",
            "posType": "infor",
            "code": "157",
            "state": "OR",
            "zipCode": "97224"
        }
    },
    {
        "guid": "geztk=",
        "streetAddress": "3080 22nd SE",
        "enableBilltrust": false,
        "blockNonStockPricing": false,
        "city": "Salem",
        "description": "Salem - #135",
        "enabled": true,
        "facebookLink": "https://www.facebook.com/Johnstone-Supply-Salem-114544653626356",
        "faxNumber": "(503) 779-2677",
        "hardiRegionName": "Western",
        "hideLsp": false,
        "instagramLink": "https://www.instagram.com/johnstonenw/",
        "linkedinLink": "https://www.linkedin.com/company/johnstonenw",
        "enableLiveChat": false,
        "liveChatLicenseNumber": "",
        "enableLogin": true,
        "mainStoreCode": "157",
        "phoneNumber": "(503) 779-1094",
        "redirectUrl": "",
        "state": "OR",
        "storeCode": "135",
        "storeEmail": "customerservice.salem@johnstonenw.com",
        "storeHours": "Monday - Friday: 7:00am - 5:00pm<br>  Saturday: CLOSED<br>  Sunday: CLOSED",
        "textPhoneNumber": null,
        "twitterLink": "https://www.twitter.com/Johnstone_NW",
        "useBarcodeScanner": true,
        "useShipToPricing": true,
        "youtubeLink": "",
        "zipCode": "97302-6300",
        "useListPrice": false,
        "displayBranchInPriceBox": false,
        "displayAllOrderNotesData": false,
        "showAlternateDescription": true,
        "showAlternateDescriptionOnAddons": false,
        "maxBranchesVisible": 7,
        "usePromoCode": true,
        "releaseNumberRequired": false,
        "hideBillingAddress": false,
        "orderContactPhoneNumberRequired": false,
        "orderContactEmailRequired": true,
        "enhancedWillCallValueInternal": null,
        "excludeFromEnhancedWillCallInternal": null,
        "enableConfirmEmail": true,
        "enforceAddressValidation": true,
        "useRequiredByDate": false,
        "requiredByDateRequired": false,
        "enableReferral": false,
        "referralRequired": false,
        "enableCreditCard": false,
        "enableCheckoutOrderLimit": false,
        "useNewContact": false,
        "hideSubstituteProductsOnCart": false,
        "overrideAvailabilityMessage": false,
        "hideOrderStatus": true,
        "hideNewAddress": false,
        "hideAddToCartOnBidsAndQuotes": false,
        "mainStore": {
            "country": "US",
            "currency": "USD",
            "description": "Tigard, OR - 16650 SW 72nd Ave. #100",
            "enabled": true,
            "name": "Tigard - #157",
            "posType": "infor",
            "code": "157",
            "state": "OR",
            "zipCode": "97224"
        }
    }
];